### ISSUE TITLE
Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

### ISSUE THREAD

**Issue by leonardo-720** [OneSignal/onesignal-expo-plugin#230] opened 2024-05-24 16:20 UTC
### How can we help?

when I add the call to start OneSignal using
OneSignal.initialize(....);

displays the error 

Could not load RNOneSignal native module. Make sure native dependencies are properly linked.

how can I solve this?

### OneSignal Expo SDK version

5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rgomezp** [comment] 2024-06-20 18:47
Duplicate of https://github.com/OneSignal/react-native-onesignal/issues/1345

Please see that issue for assistance

**Closed by rgomezp** 2024-06-20 18:47 UTC
