### ISSUE TITLE
[question]: cannot run locally with `run:ios`

### ISSUE THREAD

**Issue by peeomid** [OneSignal/onesignal-expo-plugin#78] opened 2022-04-08 09:03 UTC
### How can we help?

Hi,

I'm trying to follow the guide from [here](https://documentation.onesignal.com/docs/react-native-expo-sdk-setup) to add OneSignal in.
So I'm just running `expo run:ios` to have it running locally first (not build with eas cloud), however, it couldn't build.
Are there any other steps needed besides those listed in the document?

Thanks

### OneSignal Expo SDK version

1.0.0

### Platform

iOS

### Relevant log output

```Shell
expo run:ios
✔ Created native project | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more.

✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 2111ms
	onesignal-expo-plugin: Couldn't read file:node_modules/onesignal-expo-plugin/build/support/serviceExtensionFiles/NotificationService.h
(node:92532) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'node_modules/onesignal-expo-plugin/build/support/serviceExtensionFiles/NotificationService.h'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Config synced
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Unable to find a target named `OneSignalNotificationServiceExtension` in project `Buzzbike.xcodeproj`, did find `Buzzbike`.

› Planning build

› 0 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
To view more error logs, try building the app with Xcode directly, by opening /Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Buzzbike.xcodeproj.

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Buzzbike.xcodeproj -configuration Debug -scheme Buzzbike -destination id=FF042B5A-7013-4044-B380-8A25312579C6

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 59a67742d7c91632124a84ee6622b65c
Build description path: /Users/luan/Library/Developer/Xcode/DerivedData/Buzzbike-atvmsyprpckdeedqwjobpqcpyxjy/Build/Intermediates.noindex/XCBuildData/59a67742d7c91632124a84ee6622b65c-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
/Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Pods/Target Support Files/Pods-Buzzbike/Pods-Buzzbike.debug.xcconfig:1:1: error: unable to open file (in target "Buzzbike" in project "Buzzbike")
/Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Pods/Target Support Files/Pods-Buzzbike/Pods-Buzzbike.debug.xcconfig:1:1: error: unable to open file (in target "Buzzbike" in project "Buzzbike")
/Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Pods/Target Support Files/Pods-Buzzbike/Pods-Buzzbike.debug.xcconfig:1:1: error: unable to open file (in target "Buzzbike" in project "Buzzbike")
/Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/ios/Pods/Target Support Files/Pods-Buzzbike/Pods-Buzzbike.debug.xcconfig:1:1: error: unable to open file (in target "Buzzbike" in project "Buzzbike")


** BUILD FAILED **

Build logs written to /Users/luan/Development/Buzzbike/buzzbike-mobile/packages/mobile/.expo/xcodebuild.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peeomid** [comment] 2022-04-13 01:58
This is due to the same issue with #81 as I'm using a monorepo. Workaround is to unhoisting `onesignal-expo-plugin`, then I can run it locally.

**Comment by rgomezp** [comment] 2022-04-14 17:47
Duplicate of #81

**Closed by rgomezp** 2022-04-14 17:47 UTC
